title: Jonathan Lane
permalink: pretty
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
search_enabled: true
nav_enabled: true
collections:
  projects:
    output: true

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap