title: Jonathan Lane
permalink: pretty
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

search_enabled: true
aux_links:
  "Issues":
    - "https://github.com/jglane/jglane.github.io/issues"
  "Source on GitHub":
    - "https://github.com/jglane/jglane.github.io"

collections:
  projects:
    output: true