plugins:
- jekyll-remote-theme
remote_theme: pmarsceill/just-the-docs

title: Jonathan Lane
permalink: pretty
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
search_enabled: true
nav_enabled: true